spring.application.name=sistema-academico
spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_academico
spring.datasource.username=${USUARIO}
spring.datasource.password=${SENHA}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=academico
spring.flyway.validate-on-migrate=false
logging.level.org.flywaydb=DEBUG